import { CountdownSettingsStateData } from "../../countdown-provider/types";
import { CountdownThemeStateData } from "../../countdown-theme-provider/types";
import useMockEditorSettings from "./useMockEditorSettings";

interface UseEditorSettingsProps {
  /** if true load the mock data of the editor settings */
  isMockMode?: boolean;
}

export interface UseEditorSettingsAPIResponse {
  settings: CountdownSettingsStateData | undefined;
  theme: CountdownThemeStateData | undefined;
  isLoading?: boolean;
  isError?: any;
}

/**
 * Hook used to call the API to retrieve the data generated by the editor.
 */
export default function useEditorSettings({
  isMockMode,
}: UseEditorSettingsProps): UseEditorSettingsAPIResponse {
  if (isMockMode) {
    return useMockEditorSettings();
  }

  return {
    settings: undefined,
    theme: undefined,
    isLoading: false,
    isError: undefined,
  };
}
