import { CountdownTimerEditorStateData } from "../../countdown-provider/types";
import useMockEditorSettings from "./useMockEditorSettings";

interface UseEditorSettingsProps {
  /** if true load the mock data of the editor settings */
  isMockMode?: boolean;
}

interface UseEditorSettings {
  editorSettings: CountdownTimerEditorStateData | undefined;
  isLoading?: boolean;
  isError?: any;
}

/**
 * Hook used to call the API to retrieve the data generated by the editor.
 */
export default function useEditorSettings({
  isMockMode,
}: UseEditorSettingsProps): UseEditorSettings {
  if (isMockMode) {
    return useMockEditorSettings();
  }

  return {
    editorSettings: undefined,
    isLoading: false,
    isError: undefined,
  };
}
