import { PropertyEditorSettingsStateData } from "../../types";
import useContextEditorSettings from "./useContextEditorSettings";
import useMockEditorSettings from "./useMockEditorSettings";

interface UseEditorSettingsProps {
  /** if true load the mock data of the editor settings */
  isMockMode?: boolean;
  /** if true the data came from the editor state context */
  isEditorMode?: boolean;
}

interface UseEditorSettings {
  editorSettings: PropertyEditorSettingsStateData | undefined;
  isLoading?: boolean;
  isError?: any;
}

/**
 * Hook used to call the API to retrieve the data generated by the editor.
 */
export default function useEditorSettings({
  isMockMode,
  isEditorMode,
}: UseEditorSettingsProps): UseEditorSettings {
  if (isEditorMode) {
    return useContextEditorSettings();
  }

  // if (isMockMode) {
  //   return useMockEditorSettings();
  // }

  return {
    editorSettings: undefined,
    isLoading: false,
    isError: undefined,
  };
}
