import { useEffect, useState } from "react";

import useCountdownSelector from "../../countdown-widget-provider/hooks/useCountdownSelector";
import { SettingsStateData } from "../../countdown-widget-provider/types";
import { findById } from "../../countdown-widget-rest-api/services/find-by-id";
import { EditorSettings } from "../../countdown-widget-rest-api/types";
import useThemeSelector from "../../countdown-widget-theme-provider/hooks/useThemeSelector";
import { CountdownWidgetThemeStateData } from "../../countdown-widget-theme-provider/types";
import targetDate from "../../editor/editor-properties/components/target-date/target-date";
import { Countdown } from "../types";

interface UseEditorSettingsProps {
  /** if true load the mock data of the editor settings */
  isMockMode?: boolean;
  /** The current countdown rendered to the DOM by data-id attribute.
   * This value must be set to NULL if the component is used inside the editor
   */
  current?: Countdown["id"] | null | undefined;
}

export interface UseEditorSettingsAPIResponse {
  settings?: SettingsStateData;
  theme?: CountdownWidgetThemeStateData;
  isLoading?: boolean;
  isError?: any;
}

/**
 * Retrieves the data generated by the editor through REST API call.
 *
 * @param isMockMode if true load the mock data of the editor settings. Set manually in dev environment.
 * @param current the current countdown ID
 *     *** WHEN WORKING WITH THE EDITOR ***
 *    - it is must set to NULL
 *
 *    *** WHEN WORKING WITH THE COUNTDOWN WIDGET ***
 *    - it is provided by the [data-id] attribute when the user add the shortcode with the id attribute in the page.
 */
export default function useEditorSettings({
  current,
}: UseEditorSettingsProps): UseEditorSettingsAPIResponse {
  const [isError, setIsError] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const { setTargetDate, setTargetTimezone } = useCountdownSelector();
  const { setTimer, setTitle } = useThemeSelector();

  useEffect(() => {
    findById(current)
      .then((res) => {
        if (res.code === "error") {
          setIsError(true);
        }

        const { data } = res;

        if (data.payload) {
          const settingsParsed: EditorSettings = JSON.parse(
            data.payload.settings
          );

          if (settingsParsed) {
            const { targetDate, targetTimezone, timer, title } = settingsParsed;

            targetDate && setTargetDate(targetDate);
            targetTimezone && setTargetTimezone(targetTimezone);
            timer && setTimer(timer);
            title && setTitle(title);
          }
        }

        setIsLoading(false);
      })
      .catch(() => {
        setIsError(true);
        setIsLoading(false);
      });
  }, []);

  return {
    isLoading,
    isError,
  };
}
